# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_milkcat_raw', [dirname(__file__)])
        except ImportError:
            import _milkcat_raw
            return _milkcat_raw
        if fp is not None:
            try:
                _mod = imp.load_module('_milkcat_raw', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _milkcat_raw = swig_import_helper()
    del swig_import_helper
else:
    import _milkcat_raw
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def milkcat_init(*args):
  return _milkcat_raw.milkcat_init(*args)
milkcat_init = _milkcat_raw.milkcat_init

def milkcat_delete(*args):
  return _milkcat_raw.milkcat_delete(*args)
milkcat_delete = _milkcat_raw.milkcat_delete

def milkcat_process(*args):
  return _milkcat_raw.milkcat_process(*args)
milkcat_process = _milkcat_raw.milkcat_process

def milkcat_next(*args):
  return _milkcat_raw.milkcat_next(*args)
milkcat_next = _milkcat_raw.milkcat_next

def milkcat_get_word(*args):
  return _milkcat_raw.milkcat_get_word(*args)
milkcat_get_word = _milkcat_raw.milkcat_get_word

def milkcat_get_part_of_speech_tag(*args):
  return _milkcat_raw.milkcat_get_part_of_speech_tag(*args)
milkcat_get_part_of_speech_tag = _milkcat_raw.milkcat_get_part_of_speech_tag

def milkcat_get_word_type(*args):
  return _milkcat_raw.milkcat_get_word_type(*args)
milkcat_get_word_type = _milkcat_raw.milkcat_get_word_type

def milkcat_get_error_message():
  return _milkcat_raw.milkcat_get_error_message()
milkcat_get_error_message = _milkcat_raw.milkcat_get_error_message
# This file is compatible with both classic and new-style classes.


